### ISSUE TITLE
Which packages version did you tested?

### ISSUE THREAD

**Issue by hiratam1998** [PietroMSB/MG2N2#1]

**Comment by PietroMSB** [comment]
Hi, thank you for your question. I used the following package versions both for elaborating the data, for training the network, and generating graphs:

numpy==1.19.2
scipy==1.5.2
matplotlib==3.3.2
networkx==2.5
tensorflow==1.14.0

I am also adding this information into the readme, so it is a bit clearer.

**Comment by hiratam1998** [comment]
Thanks for your quick response!!!

**Comment by PietroMSB** [comment]
You are welcome! I hope my repository will be useful for your studies xD
