### ISSUE TITLE
Viewing the generated graphs

### ISSUE THREAD

**Issue by yash2002vardhan** [PietroMSB/MG2N2#4]
The images folder in the Generated directory (after running the generate_graphs.py file) is empty and the Graphs directory has the graphs but they have an extension .pkl with them. So how can I view the generated graphs ?

**Comment by PietroMSB** [comment]
They are serialized with the pickle package (.pkl file). You need a python script to open them and visualize them as tensors or molecules (using RdKit). Actually, the images are rendered with RdKit and saved along with the graphs by "generate_graphs.py": you can find them in the "Images" subfolder with the same numbering of the graphs.

**Comment by yash2002vardhan** [comment]
I am aware of these things, but when I am trying to visualise them using RdKit, I am getting a graph with coloured nodes and indices rather than the actually chemical symbol of the atom. I want them in the manner you have presented in the research article associated with the code here.

**Comment by PietroMSB** [comment]
Actually, in the paper, all the molecules rendered with RdKit render only coloured nodes and edges. The representations with chemical symbols were created with PowerPoint.

**Comment by yash2002vardhan** [comment]
gotcha, thanks

**Comment by yash2002vardhan** [comment]
!!
